# build the project
tasks:
  - name: Workspace Setup
    command: >
      source /workspace/pep-gitpod-workspace/.setup_workspace.sh
  - name: Autocompletion
    command: >
      source /workspace/pep-gitpod-workspace/revpro-autocomplete.sh
vscode:
  extensions:
    - vscjava.vscode-java-pack
