on:
  fork:
jobs:
  createFile:
    name: Update .setup.rb
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: 1arp/create-a-file-action@0.2
        with:
          path: '.'
          file: '.github.env'
          content: |
            ${{GITHUB_REPOSITORY_OWNER}}
            ${{github.repository}}
            ${{GITHUB_ACTOR}}
